all:
	cd Demo1
	nmake
	cd ..

	cd Demo2
	nmake
	cd ..

	cd Demo3
	nmake
	cd ..

	cd Demo4
	nmake
	cd ..

clean:
	cd Demo1
	nmake clean
	cd ..

	cd Demo2
	nmake clean
	cd ..

	cd Demo3
	nmake clean
	cd ..

	cd Demo4
	nmake clean
	cd ..
